"I attempted to run \"calculate_distance.py\" multiple times with an invalid API key, receiving the same error message each time. I then received a new command to update the API"